global using Core.Entities;
global using Core.Interfaces;
global using Infrastructure.Config;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using StackExchange.Redis;
global using Stripe;
global using System.Text.Json;
global using Product = Core.Entities.Product;
