global using Address = Core.Entities.Address;
global using Core.Entities;
global using Core.Entities.OrderAggregate;
global using Core.Interfaces;
global using File = System.IO.File;
global using Infrastructure.Config;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Order = Core.Entities.OrderAggregate.Order;
global using Product = Core.Entities.Product;
global using StackExchange.Redis;
global using Stripe;
global using System.Collections.Concurrent;
global using System.Reflection;
global using System.Text.Json;
