global using Address = Core.Entities.Address;
global using API.DTOs;
global using API.Errors;
global using API.Extensions;
global using API.Middleware;
global using API.RequestHelpers;
global using API.SignalR;
global using Core.Entities;
global using Core.Entities.OrderAggregate;
global using Core.Interfaces;
global using Core.Specifications;
global using Infrastructure.Data;
global using Infrastructure.Data.Factory;
global using Infrastructure.Services;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.SignalR;
global using Microsoft.EntityFrameworkCore;
global using Order = Core.Entities.OrderAggregate.Order;
global using Product = Core.Entities.Product;
global using Scalar.AspNetCore;
global using StackExchange.Redis;
global using static System.Console;
global using Stripe;
global using System.Collections.Concurrent;
global using System.ComponentModel.DataAnnotations;
global using System.Net;
global using System.Security.Authentication;
global using System.Security.Claims;
global using System.Text.Json;